# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload

on:
  release:
    types: [published]

# .github/workflows/ci-cd.yml
jobs:
    publish:
      name: Upload a release to PyPI
      runs-on: ubuntu-latest
      permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            repository-url: https://test.pypi.org/legacy/
