# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload

on:
  release:
    types: [published]

# .github/workflows/ci-cd.yml
jobs:
    publish:
      name: Upload a release to PyPI
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: 3.9
            
        - name: Install dependencies
          run: |
              python -m pip install flit

        - name: Publish
          env:
            FLIT_INDEX_URL: https://test.pypi.org/legacy/
            FLIT_USERNAME: __token__
            FLIT_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          run: python -m flit publish
